---
- name: SDWAN Lab1 — Basic Connectivity Check
  hosts: localhost
  gather_facts: no
  collections:
    - cisco.catalystwan

  vars_files:
    - vars.yml

  tasks:
    - name: Get Manager Info
      cisco.catalystwan.server_info:
        manager_credentials:
          url: "{{ vmanage_url }}"
          username: "{{ vmanage_username }}"
          password: "{{ vmanage_password }}"
      register: mgr

    - name: Show Manager Info
      debug:
        var: mgr

    - name: Get Devices
      cisco.catalystwan.devices_info:
        manager_credentials:
          url: "{{ vmanage_url }}"
          username: "{{ vmanage_username }}"
          password: "{{ vmanage_password }}"
        device_category: vedges
      register: devices

    - name: Show Devices
      debug:
        var: devices
