---
- name: SDWAN Lab2 — Fabric Health Checks
  hosts: localhost
  gather_facts: no
  collections:
    - cisco.catalystwan

  vars_files:
    - vars.yml

  vars:
    # Health check parameters
    fabric_health_name: "lab2-fabric-health"
    health_check_types:
      - "control_connections"
      - "orchestrator_connections"
      - "device_system_status"
      - "bfd"
      - "omp"
    timeout: 60
    retry: 3

  tasks:

    - name: Trigger health checks on fabric
      cisco.catalystwan.health_checks:
        manager_credentials:
          url: "{{ vmanage_url }}"
          username: "{{ vmanage_username }}"
          password: "{{ vmanage_password }}"
        check_type: "{{ item }}"
      loop: "{{ health_check_types }}"
      register: health_report
      retries: 3
      delay: 10

    - name: Show health report
      debug:
        var: health_report.results

    - name: Fail if any health check is critical
      fail:
        msg: "Fabric health check returned critical issues: {{ item.data }}"
      loop: "{{ health_report.results }}"
      when: item.data | selectattr("status", "equalto", "critical") | list | length > 0
