---
- name: SDWAN Lab 1 - Basic Catalyst WAN Connectivity and Device Discovery
  hosts: localhost
  gather_facts: no
  collections:
    - cisco.catalystwan

  vars_files:
    - vars.yml

  tasks:
    - name: Discover all Catalyst WAN devices
      cisco.catalystwan.devices_info:
        manager_credentials:
          url: "{{ vmanage_url }}"
          username: "{{ vmanage_username }}"
          password: "{{ vmanage_password }}"
      register: all_devices

    - name: Categorize devices by type
      set_fact:
        vmanage_devices: "{{ all_devices.devices | selectattr('device_type', 'equalto', 'vmanage') | list }}"
        vsmart_devices: "{{ all_devices.devices | selectattr('device_type', 'equalto', 'vsmart') | list }}"
        vbond_devices: "{{ all_devices.devices | selectattr('device_type', 'equalto', 'vbond') | list }}"
        vedge_devices: "{{ all_devices.devices | selectattr('device_type', 'match', '.*edge.*') | list }}"

    - name: Display device summary
      debug:
        msg: "Found {{ all_devices.devices | length }} total devices: {{ vmanage_devices | length }} vManage, {{ vsmart_devices | length }} vSmart, {{ vbond_devices | length }} vBond, {{ vedge_devices | length }} vEdge"

    - name: Display vManage controllers
      debug:
        msg: "vManage Controllers:"
      when: vmanage_devices | length > 0

    - name: Show vManage details
      debug:
        msg: "  - {{ item.host_name | default('Unknown') }} ({{ item.system_ip | default('No IP') }}) - Status: {{ item.reachability | default('Unknown') }}"
      loop: "{{ vmanage_devices }}"
      when: vmanage_devices | length > 0

    - name: Display vSmart controllers
      debug:
        msg: "vSmart Controllers:"
      when: vsmart_devices | length > 0

    - name: Show vSmart details
      debug:
        msg: "  - {{ item.host_name | default('Unknown') }} ({{ item.system_ip | default('No IP') }}) - Status: {{ item.reachability | default('Unknown') }}"
      loop: "{{ vsmart_devices }}"
      when: vsmart_devices | length > 0

    - name: Display vBond orchestrators
      debug:
        msg: "vBond Orchestrators:"
      when: vbond_devices | length > 0

    - name: Show vBond details
      debug:
        msg: "  - {{ item.host_name | default('Unknown') }} ({{ item.system_ip | default('No IP') }}) - Status: {{ item.reachability | default('Unknown') }}"
      loop: "{{ vbond_devices }}"
      when: vbond_devices | length > 0

    - name: Display vEdge routers
      debug:
        msg: "vEdge Routers:"
      when: vedge_devices | length > 0

    - name: Show vEdge details (first 10)
      debug:
        msg: "  - {{ item.host_name | default('Unknown') }} ({{ item.system_ip | default('No IP') }}) - Site: {{ item.site_id | default('N/A') }} - Status: {{ item.reachability | default('Unknown') }}"
      loop: "{{ vedge_devices[:10] }}"
      when: vedge_devices | length > 0

    - name: Show additional vEdge count
      debug:
        msg: "  ... and {{ vedge_devices | length - 10 }} more vEdge devices"
      when: vedge_devices | length > 10