---
- name: Test CSRF token
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    - name: Authenticate with vManage
      uri:
        url: "{{ vmanage_url }}/j_security_check"
        method: POST
        body: "j_username={{ vmanage_username }}&j_password={{ vmanage_password }}"
        validate_certs: false
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: login_response

    - name: Set session cookie
      set_fact:
        vmanage_cookie: "{{ login_response.cookies_string }}"

    - name: Get CSRF token
      uri:
        url: "{{ vmanage_url }}/dataservice/client/token"
        method: GET
        validate_certs: false
        return_content: yes
        headers:
          Cookie: "{{ vmanage_cookie }}"
      register: token_response

    - debug:
        var: token_response