---
# This playbook connects to a Cisco CSR1000V router and retrieves basic device information
# It shows the device hostname and IP address information for all interfaces

- name: Get CSR1000V Device Name and IP Information
  hosts: csr                    # This tells Ansible which devices to run on (defined in inventory file)
  gather_facts: no              # We don't need to collect system facts for this simple task
  connection: network_cli       # Use network CLI connection type for Cisco devices

  tasks:
    # Task 1: Get the device hostname from the running configuration
    - name: Get device hostname
      cisco.ios.ios_command:     # Use Cisco IOS command module to run CLI commands
        commands:
          - show running-config | include hostname  # This command shows only the hostname line
      register: hostname_output  # Save the command output in a variable called 'hostname_output'

    # Task 2: Get IP address information for all interfaces
    - name: Get device IP addresses
      cisco.ios.ios_command:     # Again using the IOS command module
        commands:
          - show ip interface brief  # This command shows a summary of all interfaces and their IPs
      register: ip_output        # Save this output in a variable called 'ip_output'

    # Task 3: Display the hostname in a clean format
    - name: Display device name
      debug:                     # Debug module is used to print information to the screen
        msg: "Device Name: {{ hostname_output.stdout[0] | regex_replace('hostname ', '') }}"
        # Explanation: {{ }} means we're using a variable
        # hostname_output.stdout[0] gets the first line of output
        # regex_replace removes the word 'hostname ' to show just the device name

    # Task 4: Display the IP interface information
    - name: Display device IP information
      debug:                     # Print the interface information to screen
        msg: "Device IP Interfaces: {{ ip_output.stdout[0] }}"
        # This shows the complete output from 'show ip interface brief' command