---
# Simple interactive playbook to configure NXOS interface
# Just asks for interface, IP, and mask - no complex validation

- name: Simple Interface IP Config (Easy Version)
  hosts: nxos
  gather_facts: no
  connection: network_cli

  vars_prompt:
    - name: interface_name
      prompt: "Enter interface name (e.g., Ethernet1/1)"
      private: no

    - name: ip_address
      prompt: "Enter IP address (e.g., 192.168.1.1)"
      private: no

    - name: subnet_mask
      prompt: "Enter subnet mask (e.g., 255.255.255.0)"
      private: no

  tasks:
    # Show what will be configured
    - name: Show configuration
      debug:
        msg: |
          Will configure:
          Interface: {{ interface_name }}
          IP: {{ ip_address }}
          Mask: {{ subnet_mask }}

    # Configure the interface
    - name: Configure interface
      cisco.nxos.nxos_config:
        lines:
          - ip address {{ ip_address }} {{ subnet_mask }}
          - no shutdown
        parents: interface {{ interface_name }}

    # Verify configuration
    - name: Verify configuration
      cisco.nxos.nxos_command:
        commands:
          - show interface {{ interface_name }} | include Internet
      register: verification

    # Show result
    - name: Show result
      debug:
        msg: |
          Configuration complete!
          {{ verification.stdout[0] }}