---
- name: Lab 1 - Basic Connectivity Test
  hosts: csr
  connection: network_cli
  gather_facts: no
  
  vars:
    ansible_network_os: ios
    
  tasks:
    - name: Gather device facts
      cisco.ios.ios_facts:
        gather_subset: 
          - default
          - hardware
          - interfaces
      register: device_facts
      
    - name: Display device information
      debug:
        msg: "Device: {{ ansible_net_hostname | default('Unknown') }}, IOS Version: {{ ansible_net_version | default('Unknown') }}, Serial: {{ ansible_net_serialnum | default('Unknown') }}"
        
    - name: Show memory information
      debug:
        msg: "Total Memory: {{ ansible_net_memtotal_mb | default('Unknown') }}MB, Free Memory: {{ ansible_net_memfree_mb | default('Unknown') }}MB"
        
    - name: List all interfaces
      debug:
        msg: "Available interfaces: {{ ansible_net_interfaces.keys() | list if ansible_net_interfaces is defined else 'Not available' }}"
        
    - name: Display uptime
      debug:
        msg: "Device uptime: {{ ansible_net_uptime | default('Not available') }}"
        
    - name: Show device model
      debug:
        msg: "Device model: {{ ansible_net_model | default('Not available') }}"