---
- name: Lab 8 - User Management and AAA Configuration
  hosts: csr
  connection: network_cli
  gather_facts: no
  
  vars:
    ansible_network_os: ios
    
  tasks:
    - name: Display current user configuration
      cisco.ios.ios_command:
        commands:
          - show running-config | section username
          - show users
          - show privilege
      register: current_users
      
    - name: Show current user configuration
      debug:
        var: current_users.stdout_lines
        
    - name: Create administrative users
      cisco.ios.ios_config:
        lines:
          - username netadmin privilege 15 secret NetworkAdmin123
          - username operator privilege 10 secret Operator456
          - username support privilege 5 secret Support789
          - username readonly privilege 1 secret ReadOnly123
      register: admin_users
      
    - name: Configure password policies
      cisco.ios.ios_config:
        lines:
          - security passwords min-length 8
          - security authentication failure rate 3 log
      register: password_policies
      
    - name: Enable AAA services
      cisco.ios.ios_config:
        lines:
          - aaa new-model
      register: aaa_enable
      
    - name: Configure AAA authentication
      cisco.ios.ios_config:
        lines:
          - aaa authentication login default local
          - aaa authentication login CONSOLE none
          - aaa authentication enable default enable
      register: aaa_auth
      
    - name: Configure AAA authorization
      cisco.ios.ios_config:
        lines:
          - aaa authorization exec default local
          - aaa authorization commands 15 default local
      register: aaa_authz
      
    - name: Configure console line security\n      cisco.ios.ios_config:\n        parents: line console 0\n        lines:\n          - login authentication CONSOLE\n          - exec-timeout 10 0\n      register: console_security\n      \n    - name: Configure VTY line security\n      cisco.ios.ios_config:\n        parents: line vty 0 15\n        lines:\n          - login authentication default\n          - transport input ssh\n          - exec-timeout 15 0\n          - access-class 10 in\n      register: vty_security\n      \n    - name: Configure privilege levels for commands\n      cisco.ios.ios_config:\n        lines:\n          - privilege exec level 5 show running-config\n          - privilege exec level 5 show ip route\n          - privilege exec level 10 configure terminal\n          - privilege exec level 10 copy running-config startup-config\n      register: privilege_levels\n      \n    - name: Display administrative users configuration\n      debug:\n        msg: \"Administrative users: {{ admin_users.commands | default('No changes') }}\"\n        \n    - name: Display password policies configuration\n      debug:\n        msg: \"Password policies: {{ password_policies.commands | default('No changes') }}\"\n        \n    - name: Display AAA enable configuration\n      debug:\n        msg: \"AAA enable: {{ aaa_enable.commands | default('No changes') }}\"\n        \n    - name: Display AAA authentication configuration\n      debug:\n        msg: \"AAA authentication: {{ aaa_auth.commands | default('No changes') }}\"\n        \n    - name: Display AAA authorization configuration\n      debug:\n        msg: \"AAA authorization: {{ aaa_authz.commands | default('No changes') }}\"\n        \n    - name: Display console security configuration\n      debug:\n        msg: \"Console security: {{ console_security.commands | default('No changes') }}\"\n        \n    - name: Display VTY security configuration\n      debug:\n        msg: \"VTY security: {{ vty_security.commands | default('No changes') }}\"\n        \n    - name: Display privilege levels configuration\n      debug:\n        msg: \"Privilege levels: {{ privilege_levels.commands | default('No changes') }}\"\n        \n    - name: Create access list for VTY access control\n      cisco.ios.ios_config:\n        lines:\n          - access-list 10 permit 192.168.10.0 0.0.0.255\n          - access-list 10 permit 192.168.20.0 0.0.0.255\n          - access-list 10 deny any log\n      register: vty_acl\n      \n    - name: Display VTY access control configuration\n      debug:\n        msg: \"VTY ACL: {{ vty_acl.commands | default('No changes') }}\"\n        \n    - name: Verify user and AAA configuration\n      cisco.ios.ios_command:\n        commands:\n          - show running-config | section username\n          - show running-config | section aaa\n          - show running-config | section line\n          - show users\n      register: user_verification\n      \n    - name: Show configured users\n      debug:\n        msg: \"{{ user_verification.stdout[0].split('\n') }}\"\n        \n    - name: Show AAA configuration\n      debug:\n        msg: \"{{ user_verification.stdout[1].split('\n') }}\"\n        \n    - name: Show line configuration\n      debug:\n        msg: \"{{ user_verification.stdout[2].split('\n') }}\"\n        \n    - name: Show current users\n      debug:\n        msg: \"{{ user_verification.stdout[3].split('\n') }}\"\n        \n    - name: Configure login banner\n      cisco.ios.ios_config:\n        lines:\n          - banner login ^C\n          - WARNING: Authorized access only!\n          - This system is monitored.\n          - ^C\n      register: login_banner\n      \n    - name: Display login banner configuration\n      debug:\n        msg: \"Login banner: {{ login_banner.commands | default('No changes') }}\""