---
- name: SDWAN Lab 2 - Catalyst WAN Fabric Status and Health Monitoring
  hosts: localhost
  gather_facts: no

  vars:
    vmanage_host: "10.10.20.90"
    username: "admin"
    password: "C1sco12345"
    endpoints:
      - "control/connections"
      - "bfd/sessions"
      - "omp/peers"

  tasks:
    - name: Get authentication token
      uri:
        url: "https://{{ vmanage_host }}/j_security_check"
        method: POST
        body: "j_username={{ username }}&j_password={{ password }}"
        validate_certs: no
        return_content: yes
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: login

    - name: Set authentication cookie
      set_fact:
        auth_cookie: "{{ login.cookies_string }}"

    - name: Get all devices
      command: >
        curl -k -X GET --header "Cookie: {{ auth_cookie }}" "https://{{ vmanage_host }}/dataservice/device"
      register: all_devices_raw

    - name: Parse device list
      set_fact:
        all_devices: "{{ all_devices_raw.stdout | from_json }}"

    - name: Initialize health data
      set_fact:
        control_connections: []
        bfd_sessions: []
        omp_peers: []

    - name: Get health data for each device
      command: >
        curl -k -X GET --header "Cookie: {{ auth_cookie }}" "https://{{ vmanage_host }}/dataservice/device/{{ item.1 }}?deviceId={{ item.0['system-ip'] }}"
      loop: "{{ all_devices.data | product(endpoints) | list }}"
      register: health_data_raw
      when: item.0['system-ip'] is defined

    - name: Aggregate health data
      set_fact:
        control_connections: "{{ control_connections + (item.stdout | from_json).data }}"
        bfd_sessions: "{{ bfd_sessions + (item.stdout | from_json).data }}"
        omp_peers: "{{ omp_peers + (item.stdout | from_json).data }}"
      loop: "{{ health_data_raw.results }}"
      when: item.stdout is defined and (item.stdout | from_json).data is defined

    - name: Analyze control plane health
      set_fact:
        total_control_connections: "{{ control_connections | length }}"
        up_control_connections: "{{ control_connections | selectattr('state', 'equalto', 'up') | list | length }}"
        down_control_connections: "{{ control_connections | selectattr('state', 'equalto', 'down') | list | length }}"

    - name: Analyze BFD session health
      set_fact:
        total_bfd_sessions: "{{ bfd_sessions | length }}"
        up_bfd_sessions: "{{ bfd_sessions | selectattr('state', 'equalto', 'up') | list | length }}"
        down_bfd_sessions: "{{ bfd_sessions | selectattr('state', 'equalto', 'down') | list | length }}"

    - name: Analyze OMP peer health
      set_fact:
        total_omp_peers: "{{ omp_peers | length }}"
        established_omp_peers: "{{ omp_peers | selectattr('state', 'equalto', 'up') | list | length }}"

    - name: Display control plane status
      debug:
        msg: |
          === CONTROL PLANE STATUS ===
          Total Control Connections: {{ total_control_connections | default('N/A') }}
          UP Connections: {{ up_control_connections | default('N/A') }}
          DOWN Connections: {{ down_control_connections | default('N/A') }}
          Health: {{ ((up_control_connections | default(0) | int) * 100 / (total_control_connections | default(1) | int)) | round(1) }}%

    - name: Display BFD session status
      debug:
        msg: |
          === BFD SESSION STATUS ===
          Total BFD Sessions: {{ total_bfd_sessions | default('N/A') }}
          UP Sessions: {{ up_bfd_sessions | default('N/A') }}
          DOWN Sessions: {{ down_bfd_sessions | default('N/A') }}
          Health: {{ ((up_bfd_sessions | default(0) | int) * 100 / (total_bfd_sessions | default(1) | int)) | round(1) }}%

    - name: Display OMP peer status
      debug:
        msg: |
          === OMP PEER STATUS ===
          Total OMP Peers: {{ total_omp_peers | default('N/A') }}
          Established Peers: {{ established_omp_peers | default('N/A') }}
          Health: {{ ((established_omp_peers | default(0) | int) * 100 / (total_omp_peers | default(1) | int)) | round(1) }}%
