---
# Simple playbook to toggle ONE interface on CSR1000V
# Just asks which interface and toggles it (no complex logic)

- name: Simple Interface Toggle (Easy Version)
  hosts: csr
  gather_facts: no
  connection: network_cli

  vars_prompt:
    - name: interface_name
      prompt: "Enter interface name (e.g., GigabitEthernet1)"
      private: no

  tasks:
    # Check current interface status
    - name: Check interface status
      cisco.ios.ios_command:
        commands:
          - show interface {{ interface_name }} | include line protocol
      register: current_status

    # Show current status
    - name: Show current status
      debug:
        msg: "Current status: {{ current_status.stdout[0] }}"

    # Toggle interface (shutdown if up, no shutdown if down)
    - name: Shutdown interface if it's up
      cisco.ios.ios_config:
        lines:
          - shutdown
        parents: interface {{ interface_name }}
      when: "'up' in current_status.stdout[0]"

    - name: Enable interface if it's down
      cisco.ios.ios_config:
        lines:
          - no shutdown
        parents: interface {{ interface_name }}
      when: "'down' in current_status.stdout[0]"

    # Check final status
    - name: Check final status
      cisco.ios.ios_command:
        commands:
          - show interface {{ interface_name }} | include line protocol
      register: final_status

    # Show final status
    - name: Show final status
      debug:
        msg: "Final status: {{ final_status.stdout[0] }}"