---
- name: SDWAN Lab 4 - Network Performance and Statistics Monitoring
  hosts: localhost
  gather_facts: no

  vars:
    vmanage_host: "10.10.20.90"
    username: "admin"
    password: "C1sco12345"

  tasks:
    - name: Get authentication token
      uri:
        url: "https://{{ vmanage_host }}/j_security_check"
        method: POST
        body: "j_username={{ username }}&j_password={{ password }}"
        validate_certs: no
        return_content: yes
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: login

    - name: Set authentication cookie
      set_fact:
        auth_cookie: "{{ login.cookies_string }}"

    - name: Get all devices
      command: >
        curl -k -X GET --header "Cookie: {{ auth_cookie }}" "https://{{ vmanage_host }}/dataservice/device"
      register: all_devices_raw

    - name: Parse device list
      set_fact:
        all_devices: "{{ all_devices_raw.stdout | from_json }}"

    - name: Get interface stats
      command: >
        curl -k -X GET --header "Cookie: {{ auth_cookie }}" "https://{{ vmanage_host }}/dataservice/device/interface/stats?deviceId={{ item['system-ip'] }}"
      loop: "{{ all_devices.data }}"
      register: interface_stats_raw
      when: item['system-ip'] is defined

    - name: Aggregate interface stats
      set_fact:
        interface_stats: "{{ interface_stats | default([]) + (item.stdout | from_json).data }}"
      loop: "{{ interface_stats_raw.results }}"
      when: item.stdout is defined and (item.stdout | from_json).data is defined

    - name: Create a list of interfaces with stats
      set_fact:
        interfaces_with_stats: "{{ interfaces_with_stats | default([]) + [{'ifname': item.ifname, 'rx_kbps': item['rx-kbps'] | float, 'tx_kbps': item['tx-kbps'] | float}] }}"
      loop: "{{ interface_stats }}"
      when: item['rx-kbps'] is defined and item['tx-kbps'] is defined

    - name: Analyze and display performance metrics
      block:
        - name: Analyze interface performance
          set_fact:
            total_interfaces: "{{ interface_stats | length }}"
            high_rx_interfaces: "{{ interfaces_with_stats | selectattr('rx_kbps', 'greaterthan', 10000) | list }}"
            high_tx_interfaces: "{{ interfaces_with_stats | selectattr('tx_kbps', 'greaterthan', 10000) | list }}"
            avg_rx_kbps: "{{ (interfaces_with_stats | map(attribute='rx_kbps') | sum / interfaces_with_stats | length) | round(2) if interfaces_with_stats | length > 0 else 0 }}"
            avg_tx_kbps: "{{ (interfaces_with_stats | map(attribute='tx_kbps') | sum / interfaces_with_stats | length) | round(2) if interfaces_with_stats | length > 0 else 0 }}"

        - name: Display interface performance summary
          debug:
            msg: |
              === INTERFACE PERFORMANCE SUMMARY ===
              Total Interfaces Monitored: {{ total_interfaces | default('N/A') }}
              Average Rx Throughput: {{ avg_rx_kbps | default('N/A') }} Kbps
              Average Tx Throughput: {{ avg_tx_kbps | default('N/A') }} Kbps
              Interfaces with >10000 Kbps Rx: {{ high_rx_interfaces | default([]) | length }}
              Interfaces with >10000 Kbps Tx: {{ high_tx_interfaces | default([]) | length }}
      rescue:
        - name: Handle potential errors
          debug:
            msg: "Could not analyze performance metrics. The API may have returned no data."
