---
- name: SDWAN Lab 2 - Catalyst WAN Fabric Status and Health Monitoring
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml

  vars:
    endpoints:
      - "control/connections"
      - "bfd/sessions"
      - "omp/peers"

  tasks:
    - name: Authenticate with vManage
      uri:
        url: "{{ vmanage_url }}/j_security_check"
        method: POST
        body: "j_username={{ vmanage_username }}&j_password={{ vmanage_password }}"
        validate_certs: false
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: login_response

    - name: Set session cookie
      set_fact:
        vmanage_cookie: "{{ login_response.cookies_string }}"

    - name: Get CSRF token
      uri:
        url: "{{ vmanage_url }}/dataservice/client/token"
        method: GET
        validate_certs: false
        return_content: yes
        headers:
          Cookie: "{{ vmanage_cookie }}"
      register: token_response

    - name: Set CSRF token
      set_fact:
        csrf_token: "{{ token_response.content }}"

    - name: Get all devices
      uri:
        url: "{{ vmanage_url }}/dataservice/device"
        method: GET
        validate_certs: false
        return_content: yes
        headers:
          Cookie: "{{ vmanage_cookie }}"
          X-XSRF-TOKEN: "{{ csrf_token }}"
      register: all_devices_raw

    - name: Parse device list
      set_fact:
        all_devices: "{{ all_devices_raw.json }}"

    - name: Initialize health data
      set_fact:
        control_connections: []
        bfd_sessions: []
        omp_peers: []

    - name: Get health data for each device
      uri:
        url: "{{ vmanage_url }}/dataservice/device/{{ item.1 }}?deviceId={{ item.0['system-ip'] }}"
        method: GET
        validate_certs: false
        headers:
          Cookie: "{{ vmanage_cookie }}"
          X-XSRF-TOKEN: "{{ csrf_token }}"
      loop: "{{ all_devices.data | product(endpoints) | list }}"
      register: health_data_raw
      when: item.0['system-ip'] is defined
      ignore_errors: yes

    - name: Aggregate health data
      set_fact:
        control_connections: "{{ control_connections + (item.json.data | default([])) }}"
        bfd_sessions: "{{ bfd_sessions + (item.json.data | default([])) }}"
        omp_peers: "{{ omp_peers + (item.json.data | default([])) }}"
      loop: "{{ health_data_raw.results }}"
      when: item.failed is not defined or not item.failed

    - name: Analyze control plane health
      set_fact:
        total_control_connections: "{{ control_connections | length }}"
        up_control_connections: "{{ control_connections | selectattr('state', 'equalto', 'up') | list | length }}"
        down_control_connections: "{{ control_connections | selectattr('state', 'equalto', 'down') | list | length }}"

    - name: Analyze BFD session health
      set_fact:
        total_bfd_sessions: "{{ bfd_sessions | length }}"
        up_bfd_sessions: "{{ bfd_sessions | selectattr('state', 'equalto', 'up') | list | length }}"
        down_bfd_sessions: "{{ bfd_sessions | selectattr('state', 'equalto', 'down') | list | length }}"

    - name: Analyze OMP peer health
      set_fact:
        total_omp_peers: "{{ omp_peers | length }}"
        established_omp_peers: "{{ omp_peers | selectattr('state', 'equalto', 'up') | list | length }}"

    - name: Display control plane status
      debug:
        msg: |
          === CONTROL PLANE STATUS ===
          Total Control Connections: {{ total_control_connections | default('N/A') }}
          UP Connections: {{ up_control_connections | default('N/A') }}
          DOWN Connections: {{ down_control_connections | default('N/A') }}
          Health: {{ ((up_control_connections | default(0) | int) * 100 / (total_control_connections | default(1) | int)) | round(1) }}%

    - name: Display BFD session status
      debug:
        msg: |
          === BFD SESSION STATUS ===
          Total BFD Sessions: {{ total_bfd_sessions | default('N/A') }}
          UP Sessions: {{ up_bfd_sessions | default('N/A') }}
          DOWN Sessions: {{ down_bfd_sessions | default('N/A') }}
          Health: {{ ((up_bfd_sessions | default(0) | int) * 100 / (total_bfd_sessions | default(1) | int)) | round(1) }}%

    - name: Display OMP peer status
      debug:
        msg: |
          === OMP PEER STATUS ===
          Total OMP Peers: {{ total_omp_peers | default('N/A') }}
          Established Peers: {{ established_omp_peers | default('N/A') }}
          Health: {{ ((established_omp_peers | default(0) | int) * 100 / (total_omp_peers | default(1) | int)) | round(1) }}%
