---
- name: Get CSR1000V Device Name and IP Information
  hosts: csr
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Get device hostname
      cisco.ios.ios_command:
        commands:
          - show running-config | include hostname
      register: hostname_output

    - name: Get device IP addresses
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: ip_output

    - name: Display device name
      debug:
        msg: "Device Name: {{ hostname_output.stdout[0] | regex_replace('hostname ', '') }}"

    - name: Display device IP information
      debug:
        msg: "Device IP Interfaces: {{ ip_output.stdout[0] }}"